Espresso improvements
elpassion/android-commons pull request #12
Opened 2016-12-07 12:19 UTC by ghostbuster91

2016-12-13 18:48 UTC, jozzi05 requested changes
It would be nice to also have: 
```kotlin
fun checkIntent(clazz: Class<out Activity>) {
      Intents.intended(IntentMatchers.hasComponent(clazz.name))
}
```

2016-12-13 18:48 UTC, jozzi05 commented on espresso/src/main/java/com/elpassion/android/commons/espresso/matchers/TextInputEditTextHintMatcher.kt
> +        description.appendText("has hint text from string resource on TextInputLayout: " + hintStringId)
Use kotlin syntax

2016-12-13 18:48 UTC, jozzi05 commented on espresso/src/main/java/com/elpassion/android/commons/espresso/matchers/EditTextErrorMatcher.kt
> +        description.appendText("has error text from string resource on TextInputLayout: " + textId)
Use kotlin syntax.

2016-12-13 18:48 UTC, jozzi05 commented on espresso/src/main/java/com/elpassion/android/commons/espresso/matchers/EditTextErrorMatcher.kt
> +class EditTextErrorMatcher(@StringRes private val textId: Int) : BoundedMatcher<View, EditText>(EditText::class.java) {
Change `textId ` to `errorrStringId` for consistency or change TextInputEditTextHintMatcher field to `textId`.

2016-12-13 18:49 UTC, jozzi05 commented on espresso/src/main/java/com/elpassion/android/commons/espresso/matchers/TextInputEditTextHintMatcher.kt
> +        description.appendText("has hint text from string resource on TextInputLayout: " + hintStringId)
```kotlin
"...$hintStringId"
```

2016-12-14 10:43 UTC, marcinsus approved these changes

2016-12-14 11:59 UTC, jozzi05 approved these changes

2016-12-14 12:37 UTC, merged