Rxjava test module
elpassion/android-commons pull request #32
Opened 2017-01-30 18:15 UTC by marcinsus

This is module to easiest test and mock all Observable & Completable classes.

I am not sure about Completable class, at this moment TestSubscriber leak some invalid states like next item events. Maybe we should create some wrapper (which extend Subscriber) and delegate all method to internal TestSubscriber.

2017-01-31 10:43 UTC, mareklangiewicz submitted a review, later dismissed
unit tests needed to document/show how to use all these extensions

2017-01-31 10:43 UTC, langara commented on rxjava-test/src/main/java/com/elpassion/android/commons/rxjavatest/CompletableExtension.kt
> +fun OngoingStubbing<Completable>.thenNeverending() = thenReturn(Completable.never())
I would rename it. it is not only never ending but never sending anything.
name: thenNever would suggest that it just use .never() factory method.

2017-01-31 10:43 UTC, langara commented on rxjava-test/src/main/java/com/elpassion/android/commons/rxjavatest/CompletableExtension.kt
> +fun Completable.test() = TestSubscriber<Unit>().apply { subscribe(this) }
:+1:

2017-01-31 10:43 UTC, langara commented on rxjava-test/src/main/java/com/elpassion/android/commons/rxjavatest/CompletableExtension.kt
> +fun Completable.test(assertion: TestSubscriber<Unit>.() -> Unit) = test().assertion()
:+1:

2017-01-31 10:43 UTC, langara commented on rxjava-test/src/main/java/com/elpassion/android/commons/rxjavatest/ObservableExtension.kt
> +fun <T> OngoingStubbing<Observable<T>>.thenNeverending(): OngoingStubbing<Observable<T>> = thenReturn(Observable.never())
jw

2017-01-31 14:20 UTC, OrdonTeam commented on rxjava-test/src/main/java/com/elpassion/android/commons/rxjavatest/RxSchedulersRule.kt
> +}
What's that? Why I haven't used any of that in daily development?

2017-02-01 09:08 UTC, langara commented on rxjava-test/src/test/java/com/elpassion/android/commons/rxjavatest/RxSchedulersRuleTest.kt
> +            .flatMap { threadObservable() }
how about `.map { currentThread() }`?

2017-02-02 15:33 UTC, OrdonTeam requested changes
As in commit

2017-02-02 16:02 UTC, OrdonTeam commented on settings.gradle
> +include ':pager', ':recycler', ':parcelable', ':view', ':shared-preferences', ':espresso', ':recycler-example', ':rxjava', ':rxjava-test'
Some one have to split that into multiple lines. It can be you.

2017-02-08 12:49 UTC, OrdonTeam commented
Still not finished. See `assertValuesThat`

2017-02-13 19:15 UTC, OrdonTeam approved these changes

2017-02-13 19:15 UTC, merged

2017-02-14 10:00 UTC, ghostbuster91 commented
:tada